local M = {}

-- ── color palette for dark mode ─────────────────────────────────────────────
local builtin_dark = {
    bg       = "#101212",   -- main background
    bg1      = "#101212",   -- slightly lighter (panels, float)
    bg2      = "#202028",   -- darker panel (statusline, tabline)
    bg3      = "#303038",   -- border / separator fill
    fg       = "#ffffff",   -- main text (pure white)
    fg2      = "#d0d0d0",   -- secondary text (strings, doc)
    fg3      = "#808080",   -- muted (comments, line numbers)
    red      = "#ff4444",   -- keywords, operators, errors
    teal     = "#44bbbb",   -- types, properties
    orange   = "#ff7722",   -- numbers, float literals
    blue     = "#22aaee",   -- info, tags, imports
    green    = "#44dd44",   -- git add, ok
    yellow   = "#ffdd44",   -- warnings, decorators, lifetimes
    purple   = "#dd88ff",   -- special, attributes
    sel      = "#22aaee",   -- visual selection
    search   = "#22aaee",   -- search highlight bg
}

local palette_path = vim.fn.expand("~/.config/theme/palette.json")
local ok_palette, palette = pcall(vim.json.decode, table.concat(vim.fn.readfile(palette_path), "\n"))
local c_dark = ok_palette and (palette.nvim_dark or palette.dark) or builtin_dark

-- ── helper: make a hl entry ──────────────────────────────────────────────────
local function hl(fg, bg, opts)
    local t = {}
    if fg  then t.fg   = fg  end
    if bg  then t.bg   = bg  end
    if opts then for k,v in pairs(opts) do t[k]=v end end
    return t
end

-- ── all overrides ────────────────────────────────────────────────────────────
local dark = {

    -- ── Editor UI ────────────────────────────────────────────────────────────
    Normal            = hl(c_dark.fg,  nil),
    NormalFloat       = hl(c_dark.fg,  nil),
    NormalNC          = hl(c_dark.fg,  nil),
    SignColumn        = hl(nil,        nil),
    LineNr            = hl(c_dark.fg3, nil),
    CursorLineNr      = hl(c_dark.red, c_dark.bg1, {bold=true}),
    CursorLine        = hl(nil,        c_dark.bg1),
    ColorColumn       = hl(nil,        c_dark.bg1),
    Visual            = hl(nil,        c_dark.sel),
    VisualNOS         = hl(nil,        c_dark.sel),
    Search            = hl(c_dark.bg,  c_dark.search),
    IncSearch         = hl(c_dark.fg,  c_dark.search, {bold=true}),
    CurSearch         = hl(c_dark.fg,  c_dark.search, {bold=true}),
    MatchParen        = hl(nil,        c_dark.bg3, {bold=true}),
    EndOfBuffer       = hl(c_dark.bg3, nil),
    Folded            = hl(c_dark.fg3, c_dark.bg2),
    FoldColumn        = hl(c_dark.bg3, nil),
    Conceal           = hl(c_dark.fg3, nil),
    NonText           = hl(c_dark.bg3, nil),
    SpecialKey        = hl(c_dark.fg3, nil),
    Whitespace        = hl(c_dark.bg3, nil),
    WinSeparator      = hl(c_dark.bg3, nil),
    VertSplit         = hl(c_dark.bg3, nil),
    Title             = hl(c_dark.fg,  nil, {bold=true}), 

    -- ── Statusline / tabline ─────────────────────────────────────────────────
    StatusLine        = hl(c_dark.fg2, c_dark.bg2),
    StatusLineNC      = hl(c_dark.fg3, c_dark.bg2),
    TabLine           = hl(c_dark.fg3, c_dark.bg2),
    TabLineFill       = hl(nil,        c_dark.bg2),
    TabLineSel        = hl(c_dark.fg,  c_dark.bg, {bold=true}),
    WildMenu          = hl(c_dark.fg,  c_dark.sel),

    -- ── Popup / completion ───────────────────────────────────────────────────
    Pmenu             = hl(c_dark.fg,  c_dark.bg2),
    PmenuSel          = hl(c_dark.fg,  c_dark.sel, {bold=true}),
    PmenuSbar         = hl(nil,        c_dark.bg2),
    PmenuThumb        = hl(nil,        c_dark.fg3),
    FloatBorder       = hl(c_dark.bg3, nil),
    FloatTitle        = hl(c_dark.fg2, nil, {bold=true}),

    -- ── Messages ─────────────────────────────────────────────────────────────
    ErrorMsg          = hl(c_dark.red,    nil, {bold=true}),
    WarningMsg        = hl(c_dark.yellow, nil),
    ModeMsg           = hl(c_dark.fg,     nil, {bold=true}),
    MoreMsg           = hl(c_dark.green,  nil),
    Question          = hl(c_dark.blue,   nil),

    -- ── Classic syntax groups ─────────────────────────────────────────────────
    Comment           = hl(c_dark.fg3,   nil, {italic=false}),
    Constant          = hl(c_dark.fg,    nil),
    String            = hl(c_dark.fg2,   nil),
    Character         = hl(c_dark.fg2,   nil),
    Number            = hl(c_dark.orange, nil),
    Float             = hl(c_dark.orange, nil),
    Boolean           = hl(c_dark.red,   nil, {bold=true}),
    Identifier        = hl(c_dark.fg,    nil),
    Function          = hl(c_dark.fg,    nil, {bold=true}),
    Statement         = hl(c_dark.red,   nil, {bold=true}),
    Conditional       = hl(c_dark.red,   nil, {bold=true}),
    Repeat            = hl(c_dark.red,   nil, {bold=true}),
    Label             = hl(c_dark.red,   nil, {bold=true}),
    Operator          = hl(c_dark.red,   nil),
    Keyword           = hl(c_dark.red,   nil, {bold=true}),
    Exception         = hl(c_dark.red,   nil, {bold=true}),
    PreProc           = hl(c_dark.red,   nil),
    Include           = hl(c_dark.blue,  nil),
    Define            = hl(c_dark.red,   nil),
    Macro             = hl(c_dark.red,   nil, {bold=true}),
    PreCondit         = hl(c_dark.red,   nil),
    StorageClass      = hl(c_dark.red,   nil, {bold=true}),
    Structure         = hl(c_dark.teal,  nil, {bold=true}),
    Typedef           = hl(c_dark.teal,  nil, {bold=true}),
    Type              = hl(c_dark.teal,  nil, {bold=true}),
    Special           = hl(c_dark.blue, nil),
    SpecialChar       = hl(c_dark.orange, nil),
    Tag               = hl(c_dark.blue,  nil),
    Delimiter         = hl(c_dark.fg3,   nil),
    SpecialComment    = hl(c_dark.fg3,   nil, {italic=false}),
    Debug             = hl(c_dark.red,   nil),
    Underlined        = hl(nil,          nil, {underline=true}),
    Error             = hl(c_dark.red,   nil, {bold=true}),
    Todo              = hl(c_dark.blue,  c_dark.bg1, {bold=true}),
    Variable          = hl(c_dark.fg,    nil, {italic=true}),

    -- ── Treesitter — generic ─────────────────────────────────────────────────
    ["@comment"]                    = hl(c_dark.fg3,    nil, {italic=false}),
    ["@comment.documentation"]      = hl(c_dark.fg3,    nil, {italic=false}),
    ["@error"]                      = hl(c_dark.red,    nil, {bold=true}),

    ["@keyword"]                    = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.function"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.operator"]           = hl(c_dark.red,    nil),
    ["@keyword.return"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.conditional"]        = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.conditional.ternary"]= hl(c_dark.red,    nil),
    ["@keyword.repeat"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.exception"]          = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.import"]             = hl(c_dark.blue,   nil),
    ["@keyword.directive"]          = hl(c_dark.red,    nil),
    ["@keyword.directive.define"]   = hl(c_dark.red,    nil),
    ["@keyword.coroutine"]          = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.debug"]              = hl(c_dark.red,    nil),

    ["@operator"]                   = hl(c_dark.red,    nil),
    ["@punctuation.bracket"]        = hl(c_dark.fg3,    nil),
    ["@punctuation.delimiter"]      = hl(c_dark.fg3,    nil),
    ["@punctuation.special"]        = hl(c_dark.orange, nil),

    ["@variable"]                   = hl(c_dark.fg,     nil),
    ["@variable.builtin"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@variable.parameter"]         = hl(c_dark.teal,   nil),
    ["@variable.parameter.builtin"] = hl(c_dark.teal,   nil, {italic=true}),
    ["@variable.member"]            = hl(c_dark.teal,   nil),

    ["@constant"]                   = hl(c_dark.fg,     nil),
    ["@constant.builtin"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@constant.macro"]             = hl(c_dark.red,    nil, {bold=true}),

    ["@string"]                     = hl(c_dark.fg2,    nil),
    ["@string.documentation"]       = hl(c_dark.fg2,    nil, {italic=true}),
    ["@string.escape"]              = hl(c_dark.orange, nil),
    ["@string.special"]             = hl(c_dark.orange, nil),
    ["@string.special.url"]         = hl(c_dark.blue,   nil, {underline=true}),
    ["@string.special.path"]        = hl(c_dark.blue,   nil),
    ["@string.regexp"]              = hl(c_dark.orange, nil),

    ["@character"]                  = hl(c_dark.fg2,    nil),
    ["@character.special"]          = hl(c_dark.orange, nil),
    ["@number"]                     = hl(c_dark.orange, nil),
    ["@number.float"]               = hl(c_dark.orange, nil),
    ["@boolean"]                    = hl(c_dark.red,    nil, {bold=true}),

    ["@type"]                       = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.builtin"]               = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.qualifier"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@type.definition"]            = hl(c_dark.teal,   nil, {bold=true}),

    ["@attribute"]                  = hl(c_dark.yellow, nil),
    ["@attribute.builtin"]          = hl(c_dark.yellow, nil),

    ["@function"]                   = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.call"]              = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.builtin"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@function.macro"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@function.method"]            = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.method.call"]       = hl(c_dark.fg,     nil, {bold=true}),

    ["@constructor"]                = hl(c_dark.teal,   nil, {bold=true}),
    ["@property"]                   = hl(c_dark.teal,   nil),
    ["@field"]                      = hl(c_dark.teal,   nil),
    ["@tag"]                        = hl(c_dark.blue,   nil, {bold=true}),
    ["@tag.attribute"]              = hl(c_dark.teal,   nil),
    ["@tag.delimiter"]              = hl(c_dark.fg3,    nil),

    ["@module"]                     = hl(c_dark.fg,     nil),
    ["@module.builtin"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@label"]                      = hl(c_dark.red,    nil),

    ["@markup.heading"]             = hl(c_dark.fg,     nil, {bold=true}),
    ["@markup.heading.1"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@markup.heading.2"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@markup.heading.3"]           = hl(c_dark.orange, nil, {bold=true}),
    ["@markup.heading.4"]           = hl(c_dark.orange, nil, {bold=true}),
    ["@markup.raw"]                 = hl(c_dark.fg2,    c_dark.bg1),
    ["@markup.raw.block"]           = hl(c_dark.fg2,    c_dark.bg1),
    ["@markup.link"]                = hl(c_dark.blue,   nil, {underline=true}),
    ["@markup.link.label"]          = hl(c_dark.blue,   nil),
    ["@markup.link.url"]            = hl(c_dark.blue,   nil, {underline=true}),
    ["@markup.italic"]              = hl(nil,           nil, {italic=true}),
    ["@markup.strong"]              = hl(nil,           nil, {bold=true}),
    ["@markup.strikethrough"]       = hl(c_dark.fg3,    nil, {strikethrough=true}),
    ["@markup.list"]                = hl(c_dark.red,    nil),
    ["@markup.list.checked"]        = hl(c_dark.green,  nil),
    ["@markup.list.unchecked"]      = hl(c_dark.fg3,    nil),
    ["@markup.quote"]               = hl(c_dark.fg,     nil),
    ["@markup.math"]                = hl(c_dark.teal,   nil),
    ["@punctuation.special.typst"]  = hl(c_dark.red,    nil, {bold=true}),

    -- Typst: several gray levels and red shades keep dense documents legible
    ["@markup.heading.1.typst"]     = hl("#ff5c5c", nil, {bold=true}),
    ["@markup.heading.2.typst"]     = hl("#d76a6a", nil, {bold=true}),
    ["@markup.heading.3.typst"]     = hl("#f5f5f5", nil, {bold=true}),
    ["@markup.heading.4.typst"]     = hl("#b8b8b8", nil, {bold=true}),
    ["@markup.heading.5.typst"]     = hl("#9b7b7b", nil, {bold=true}),
    ["@markup.heading.6.typst"]     = hl("#888888", nil, {bold=true}),
    ["@keyword.typst"]              = hl("#ff4d4d", nil, {bold=true}),
    ["@keyword.import.typst"]       = hl("#d76a6a", nil, {bold=true}),
    ["@keyword.conditional.typst"]  = hl("#ff5c5c", nil),
    ["@keyword.repeat.typst"]       = hl("#c94747", nil),
    ["@function.call.typst"]        = hl("#f5f5f5", nil, {bold=true}),
    ["@variable.member.typst"]      = hl("#b99a9a", nil),
    ["@constant.typst"]             = hl("#d8d8d8", nil),
    ["@number.typst"]               = hl("#d76a6a", nil),
    ["@boolean.typst"]              = hl("#ff4d4d", nil, {bold=true}),
    ["@string.typst"]               = hl("#b8b8b8", nil),
    ["@operator.typst"]             = hl("#c94747", nil),
    ["@markup.math.typst"]          = hl("#c9c9c9", nil, {italic=true}),
    ["@markup.raw.typst"]           = hl("#b8b8b8", "#222222"),
    ["@markup.link.typst"]          = hl("#d76a6a", nil, {underline=true}),
    ["@markup.link.url.typst"]      = hl("#ff5c5c", nil, {underline=true}),
    ["@markup.link.label.typst"]    = hl("#9b7b7b", nil),
    ["@markup.strong.typst"]        = hl("#f5f5f5", nil, {bold=true}),
    ["@markup.italic.typst"]        = hl("#c9c9c9", nil, {italic=true}),
    ["@punctuation.bracket.typst"]  = hl("#747474", nil),
    ["@punctuation.delimiter.typst"] = hl("#9b7b7b", nil),
    ["@comment.typst"]              = hl("#747474", nil, {italic=true}),

    ["@diff.plus"]                  = hl(c_dark.green,  nil),
    ["@diff.minus"]                 = hl(c_dark.red,    nil),
    ["@diff.delta"]                 = hl(c_dark.blue,   nil),

    -- ── C / C++ specific ─────────────────────────────────────────────────────
    ["@keyword.c"]                  = hl(c_dark.red,    nil, {bold=true}),
    ["@type.c"]                     = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.builtin.c"]             = hl(c_dark.teal,   nil, {bold=true}),
    ["@keyword.cpp"]                = hl(c_dark.red,    nil, {bold=true}),
    ["@type.cpp"]                   = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.builtin.cpp"]           = hl(c_dark.teal,   nil, {bold=true}),
    ["@keyword.directive.cpp"]      = hl(c_dark.red,    nil),
    ["@keyword.directive.define.cpp"] = hl(c_dark.red,  nil, {bold=true}),
    ["@string.cpp"]                 = hl(c_dark.fg2,    nil),
    ["@number.cpp"]                 = hl(c_dark.orange, nil),
    ["@operator.cpp"]               = hl(c_dark.red,    nil),
    ["@variable.cpp"]               = hl(c_dark.fg,     nil),
    ["@variable.member.cpp"]        = hl(c_dark.teal,   nil),
    ["@function.cpp"]               = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.method.cpp"]        = hl(c_dark.fg,     nil, {bold=true}),
    ["@constructor.cpp"]            = hl(c_dark.fg,     nil, {bold=true}),
    ["@namespace.cpp"]              = hl(c_dark.fg,     nil),
    cppSTLnamespace                 = hl(c_dark.fg,     nil),
    cppSTLtype                      = hl(c_dark.teal,   nil, {bold=true}),
    cppSTLexception                 = hl(c_dark.red,    nil, {bold=true}),
    cppSTLfunction                  = hl(c_dark.fg,     nil, {bold=true}),
    cppSTLios                       = hl(c_dark.teal,   nil),
    cppSTLiterator                  = hl(c_dark.teal,   nil),
    cppSTLiterator_tag              = hl(c_dark.teal,   nil),
    cppSTLconstant                  = hl(c_dark.orange, nil),
    cppSTLconcept                   = hl(c_dark.teal,   nil, {bold=true}),

    -- ── Python specific ──────────────────────────────────────────────────────
    ["@keyword.python"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.import.python"]      = hl(c_dark.blue,   nil),
    ["@type.python"]                = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.builtin.python"]        = hl(c_dark.teal,   nil, {bold=true}),
    ["@string.python"]              = hl(c_dark.fg2,    nil),
    ["@string.documentation.python"]= hl(c_dark.fg3,    nil, {italic=true}),
    ["@number.python"]              = hl(c_dark.orange, nil),
    ["@boolean.python"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@operator.python"]            = hl(c_dark.red,    nil),
    ["@function.python"]            = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.call.python"]       = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.builtin.python"]    = hl(c_dark.red,    nil, {bold=true}),
    ["@function.method.python"]     = hl(c_dark.fg,     nil, {bold=true}),
    ["@variable.python"]            = hl(c_dark.fg,     nil),
    ["@variable.builtin.python"]    = hl(c_dark.red,    nil, {bold=true}),
    ["@variable.parameter.python"]  = hl(c_dark.teal,   nil),
    ["@attribute.python"]           = hl(c_dark.yellow, nil),
    ["@constant.python"]            = hl(c_dark.fg,     nil),
    ["@constant.builtin.python"]    = hl(c_dark.red,    nil, {bold=true}),
    ["@constructor.python"]         = hl(c_dark.teal,   nil, {bold=true}),
    ["@exception.python"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@punctuation.bracket.python"] = hl(c_dark.fg3,    nil),
    pythonBuiltin                   = hl(c_dark.red,    nil, {bold=true}),
    pythonExceptions                = hl(c_dark.red,    nil, {bold=true}),
    pythonDecorator                 = hl(c_dark.yellow, nil),
    pythonDecoratorName             = hl(c_dark.yellow, nil),
    pythonDottedName                = hl(c_dark.fg,     nil),
    pythonImport                    = hl(c_dark.blue,   nil),
    pythonFunction                  = hl(c_dark.fg,     nil, {bold=true}),
    pythonClass                     = hl(c_dark.teal,   nil, {bold=true}),
    pythonOperator                  = hl(c_dark.red,    nil),
    pythonString                    = hl(c_dark.fg2,    nil),
    pythonNumber                    = hl(c_dark.orange, nil),
    pythonComment                   = hl(c_dark.fg3,    nil, {italic=false}),

    -- ── Rust specific ────────────────────────────────────────────────────────
    ["@keyword.rust"]               = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.function.rust"]      = hl(c_dark.red,    nil, {bold=true}),
    ["@type.rust"]                  = hl(c_dark.teal,   nil, {bold=true}),
    ["@type.builtin.rust"]          = hl(c_dark.teal,   nil, {bold=true}),
    ["@string.rust"]                = hl(c_dark.fg2,    nil),
    ["@number.rust"]                = hl(c_dark.orange, nil),
    ["@operator.rust"]              = hl(c_dark.red,    nil),
    ["@function.rust"]              = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.call.rust"]         = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.macro.rust"]        = hl(c_dark.red,    nil, {bold=true}),
    ["@function.method.rust"]       = hl(c_dark.fg,     nil, {bold=true}),
    ["@variable.rust"]              = hl(c_dark.fg,     nil),
    ["@variable.builtin.rust"]      = hl(c_dark.red,    nil, {bold=true}),
    ["@variable.parameter.rust"]    = hl(c_dark.teal,   nil),
    ["@attribute.rust"]             = hl(c_dark.yellow, nil),
    ["@constant.rust"]              = hl(c_dark.orange, nil, {bold=true}),
    ["@constant.builtin.rust"]      = hl(c_dark.orange, nil, {bold=true}),
    ["@constructor.rust"]           = hl(c_dark.teal,   nil, {bold=true}),
    ["@punctuation.bracket.rust"]   = hl(c_dark.fg3,    nil),
    ["@punctuation.special.rust"]   = hl(c_dark.orange, nil),
    ["@label.rust"]                 = hl(c_dark.red,    nil),
    rustLifetime                    = hl(c_dark.yellow, nil, {italic=true}),
    rustSigil                       = hl(c_dark.red,    nil),
    rustModPath                     = hl(c_dark.fg,     nil),
    rustModPathSep                  = hl(c_dark.fg3,    nil),
    rustDerive                      = hl(c_dark.yellow, nil),
    rustDeriveTrait                 = hl(c_dark.teal,   nil, {italic=true}),
    rustTrait                       = hl(c_dark.teal,   nil, {bold=true}),
    rustEnum                        = hl(c_dark.teal,   nil, {bold=true}),
    rustEnumVariant                 = hl(c_dark.teal,   nil),
    rustStructure                   = hl(c_dark.teal,   nil, {bold=true}),
    rustSelf                        = hl(c_dark.red,    nil, {bold=true}),
    rustSuper                       = hl(c_dark.red,    nil, {bold=true}),
    rustMacro                       = hl(c_dark.red,    nil, {bold=true}),
    rustAttribute                   = hl(c_dark.yellow, nil),
    rustStorage                     = hl(c_dark.red,    nil, {bold=true}),
    rustKeyword                     = hl(c_dark.red,    nil, {bold=true}),
    rustBoolean                     = hl(c_dark.red,    nil, {bold=true}),
    rustArrowCharacter              = hl(c_dark.red,    nil),
    rustOperator                    = hl(c_dark.red,    nil),
    rustRepeat                      = hl(c_dark.red,    nil, {bold=true}),
    rustConditional                 = hl(c_dark.red,    nil, {bold=true}),
    rustString                      = hl(c_dark.fg2,    nil),
    rustStringDelimiter             = hl(c_dark.fg3,    nil),
    rustNumber                      = hl(c_dark.orange, nil),
    rustFloat                       = hl(c_dark.orange, nil),
    rustComment                     = hl(c_dark.fg3,    nil, {italic=false}),
    rustCommentLine                 = hl(c_dark.fg3,    nil, {italic=false}),
    rustCommentBlock                = hl(c_dark.fg3,    nil, {italic=false}),
    rustDocComment                  = hl(c_dark.fg3,    nil, {italic=false}),

    -- ── TeX / LaTeX specific ─────────────────────────────────────────────────
    ["@keyword.tex"]                = hl(c_dark.red,    nil, {bold=true}),
    ["@function.macro.tex"]         = hl(c_dark.red,    nil, {bold=true}),
    ["@operator.tex"]               = hl(c_dark.red,    nil),
    ["@string.tex"]                 = hl(c_dark.fg2,    nil),
    ["@string.special.tex"]         = hl(c_dark.orange, nil),
    ["@comment.tex"]                = hl(c_dark.fg3,    nil, {italic=true}),
    ["@markup.math.tex"]            = hl(c_dark.teal,   nil),
    ["@markup.heading.tex"]         = hl(c_dark.fg,     nil, {bold=true}),
    ["@markup.strong.tex"]          = hl(nil,           nil, {bold=true}),
    ["@markup.italic.tex"]          = hl(nil,           nil, {italic=true}),
    ["@markup.link.url.tex"]        = hl(c_dark.blue,   nil, {underline=true}),
    ["@punctuation.bracket.tex"]    = hl(c_dark.fg3,    nil),
    ["@punctuation.special.tex"]    = hl(c_dark.orange, nil),
    ["@variable.tex"]               = hl(c_dark.fg,     nil),
    texCmd                          = hl(c_dark.red,    nil, {bold=true}),
    texCmdPart                      = hl(c_dark.red,    nil, {bold=true}),
    texCmdDef                       = hl(c_dark.red,    nil, {bold=true}),
    texCmdEnv                       = hl(c_dark.red,    nil, {bold=true}),
    texCmdGreek                     = hl(c_dark.teal,   nil),
    texCmdMath                      = hl(c_dark.teal,   nil),
    texCmdItem                      = hl(c_dark.red,    nil, {bold=true}),
    texCmdRef                       = hl(c_dark.blue,   nil),
    texCmdCite                      = hl(c_dark.blue,   nil),
    texCmdTitle                     = hl(c_dark.red,    nil, {bold=true}),
    texEnvName                      = hl(c_dark.teal,   nil, {bold=true}),
    texMathEnvName                  = hl(c_dark.teal,   nil, {bold=true}),
    texMathOper                     = hl(c_dark.red,    nil),
    texMathDelim                    = hl(c_dark.fg3,    nil),
    texMathZone                     = hl(c_dark.teal,   nil),
    texMathZoneEnv                  = hl(c_dark.teal,   nil),
    texMathZoneX                    = hl(c_dark.teal,   nil),
    texMathZoneXX                   = hl(c_dark.teal,   nil),
    texMathZoneLI                   = hl(c_dark.teal,   nil),
    texZone                         = hl(c_dark.fg2,    nil),
    texComment                      = hl(c_dark.fg3,    nil, {italic=false}),
    texString                       = hl(c_dark.fg2,    nil),
    texArg                          = hl(c_dark.fg,     nil),
    texOpt                          = hl(c_dark.yellow, nil),
    texOptSep                       = hl(c_dark.fg3,    nil),
    texLength                       = hl(c_dark.orange, nil),
    texSpecialChar                  = hl(c_dark.orange, nil),
    texSymbol                       = hl(c_dark.red,    nil),

    -- ── Bash / Shell specific ────────────────────────────────────────────────
    ["@keyword.bash"]               = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.conditional.bash"]   = hl(c_dark.red,    nil, {bold=true}),
    ["@keyword.repeat.bash"]        = hl(c_dark.red,    nil, {bold=true}),
    ["@function.bash"]              = hl(c_dark.fg,     nil, {bold=true}),
    ["@function.call.bash"]         = hl(c_dark.fg,     nil, {bold=true}),
    ["@variable.bash"]              = hl(c_dark.fg,     nil),
    ["@variable.builtin.bash"]      = hl(c_dark.red,    nil, {bold=true}),
    ["@variable.parameter.bash"]    = hl(c_dark.teal,   nil),
    ["@string.bash"]                = hl(c_dark.fg2,    nil),
    ["@string.special.bash"]        = hl(c_dark.orange, nil),
    ["@number.bash"]                = hl(c_dark.orange, nil),
    ["@operator.bash"]              = hl(c_dark.red,    nil),
    ["@punctuation.bracket.bash"]   = hl(c_dark.fg3,    nil),
    ["@punctuation.special.bash"]   = hl(c_dark.orange, nil),
    ["@comment.bash"]               = hl(c_dark.fg3,    nil, {italic=true}),
    shCmd                           = hl(c_dark.fg,     nil, {bold=true}),
    shFunctionKey                   = hl(c_dark.red,    nil, {bold=true}),
    shFunction                      = hl(c_dark.fg,     nil, {bold=true}),
    shStatement                     = hl(c_dark.red,    nil, {bold=true}),
    shConditional                   = hl(c_dark.red,    nil, {bold=true}),
    shLoop                          = hl(c_dark.red,    nil, {bold=true}),
    shRepeat                        = hl(c_dark.red,    nil, {bold=true}),
    shExpr                          = hl(c_dark.red,    nil),
    shOption                        = hl(c_dark.fg,     nil),
    shParen                         = hl(c_dark.fg3,    nil),
    shCmdSubRegion                  = hl(c_dark.orange, nil),
    shCommandSub                    = hl(c_dark.orange, nil),
    shQuote                         = hl(c_dark.fg3,    nil),
    shDeref                         = hl(c_dark.red,    nil),
    shSpecial                       = hl(c_dark.orange, nil),
    shVariable                      = hl(c_dark.fg,     nil),
    shVarAssign                     = hl(c_dark.teal,   nil),
    shString                        = hl(c_dark.fg2,    nil),
    shNumber                        = hl(c_dark.orange, nil),
    shComment                       = hl(c_dark.fg3,    nil, {italic=false}),
    bashStatement                   = hl(c_dark.red,    nil, {bold=true}),

    -- ── LSP semantic tokens ───────────────────────────────────────────────────
    ["@lsp.type.keyword"]           = hl(c_dark.red,    nil, {bold=true}),
    ["@lsp.type.function"]          = hl(c_dark.fg,     nil, {bold=true}),
    ["@lsp.type.method"]            = hl(c_dark.fg,     nil, {bold=true}),
    ["@lsp.type.macro"]             = hl(c_dark.red,    nil, {bold=true}),
    ["@lsp.type.type"]              = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.class"]             = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.struct"]            = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.enum"]              = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.enumMember"]        = hl(c_dark.teal,   nil),
    ["@lsp.type.interface"]         = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.typeParameter"]     = hl(c_dark.teal,   nil, {italic=true}),
    ["@lsp.type.namespace"]         = hl(c_dark.fg,     nil),
    ["@lsp.type.variable"]          = hl(c_dark.fg,     nil),
    ["@lsp.type.parameter"]         = hl(c_dark.teal,   nil),
    ["@lsp.type.property"]          = hl(c_dark.teal,   nil),
    ["@lsp.type.decorator"]         = hl(c_dark.yellow, nil),
    ["@lsp.type.selfParameter"]     = hl(c_dark.red,    nil, {bold=true}),
    ["@lsp.type.builtinType"]       = hl(c_dark.teal,   nil, {bold=true}),
    ["@lsp.type.operator"]          = hl(c_dark.red,    nil),
    ["@lsp.type.lifetime"]          = hl(c_dark.yellow, nil, {italic=true}),
    ["@lsp.mod.readonly"]           = hl(nil,           nil, {bold=true}),
    ["@lsp.mod.static"]             = hl(nil,           nil, {bold=true}),
    ["@lsp.mod.deprecated"]         = hl(c_dark.fg3,    nil, {strikethrough=true}),
    ["@lsp.typemod.function.defaultLibrary"] = hl(c_dark.red, nil, {bold=true}),
    ["@lsp.typemod.variable.defaultLibrary"] = hl(c_dark.red, nil, {bold=true}),

    -- ── Codeium ───────────────────────────────────────────────────────────────
    CodeiumSuggestion               = hl(c_dark.fg3,    nil, {italic=true}),

    -- ── LSP references ────────────────────────────────────────────────────────
    LspReferenceText                = hl(nil, c_dark.bg2),
    LspReferenceRead                = hl(nil, c_dark.bg2),
    LspReferenceWrite               = hl(nil, "#3a2a1a"),
    DiagnosticError                 = hl(c_dark.red,    nil),
    DiagnosticWarn                  = hl(c_dark.yellow, nil),
    DiagnosticInfo                  = hl(c_dark.blue,   nil),
    DiagnosticHint                  = hl(c_dark.teal,   nil),
    DiagnosticUnderlineError        = hl(nil, nil, {sp=c_dark.red,    underline=true}),
    DiagnosticUnderlineWarn         = hl(nil, nil, {sp=c_dark.yellow, underline=true}),
    DiagnosticUnderlineInfo         = hl(nil, nil, {sp=c_dark.blue,   underline=true}),
    DiagnosticUnderlineHint         = hl(nil, nil, {sp=c_dark.teal,   underline=true}),
    DiagnosticVirtualTextError      = hl(c_dark.red,    c_dark.bg1),
    DiagnosticVirtualTextWarn       = hl(c_dark.yellow, c_dark.bg1),
    DiagnosticVirtualTextInfo       = hl(c_dark.blue,   c_dark.bg1),
    DiagnosticVirtualTextHint       = hl(c_dark.teal,   c_dark.bg1),

    -- ── Git ──────────────────────────────────────────────────────────────────
    GitSignsAdd                     = hl(c_dark.green,  nil),
    GitSignsChange                  = hl(c_dark.blue,   nil),
    GitSignsDelete                  = hl(c_dark.red,    nil),
    DiffAdd                         = hl(nil,           "#292929"),
    DiffChange                      = hl(nil,           "#3a2a2a"),
    DiffDelete                      = hl(nil,           "#4a1f1f"),
    DiffText                        = hl(nil,           "#633030"),

    -- ── NvChad tabufline ─────────────────────────────────────────────────────
    TbLineBufOn                     = hl(c_dark.fg,  c_dark.bg,  {bold=true}),
    TbLineBufOff                    = hl(c_dark.fg3, c_dark.bg2),
    TbLineTabOn                     = hl(c_dark.fg,  c_dark.bg,  {bold=true}),
    TbLineTabOff                    = hl(c_dark.fg3, c_dark.bg2),
    TbLineBufOnModified             = hl(c_dark.red, c_dark.bg),
    TbLineBufOffModified            = hl(c_dark.red, c_dark.bg2),
    TbLineCloseBtn                  = hl(c_dark.fg3, c_dark.bg),
    TbLineBufOnClose                = hl(c_dark.fg3, c_dark.bg),
    TbLineBufOffClose               = hl(c_dark.fg3, c_dark.bg2),
    TbLineTheme                     = hl(c_dark.fg3, c_dark.bg2),
    TbLineBackground                = hl(nil,        c_dark.bg2),

    -- ── Telescope ────────────────────────────────────────────────────────────
    TelescopeNormal                 = hl(c_dark.fg,  nil),
    TelescopeBorder                 = hl(c_dark.bg3, nil),
    TelescopePromptBorder           = hl(c_dark.bg3, nil),
    TelescopePromptNormal           = hl(c_dark.fg,  nil),
    TelescopePromptPrefix           = hl(c_dark.red, nil),
    TelescopeResultsBorder          = hl(c_dark.bg3, nil),
    TelescopeResultsNormal          = hl(c_dark.fg,  nil),
    TelescopePreviewBorder          = hl(c_dark.bg3, nil),
    TelescopePreviewNormal          = hl(c_dark.fg,  nil),
    TelescopeSelectionCaret         = hl(c_dark.red, c_dark.sel),
    TelescopeSelection              = hl(c_dark.fg,  c_dark.sel),
    TelescopeMatching               = hl(c_dark.red, nil, {bold=true}),

    -- ── nvim-tree ────────────────────────────────────────────────────────────
    NvimTreeNormal                  = hl(c_dark.fg,  nil),
    NvimTreeNormalNC                = hl(c_dark.fg,  nil),
    NvimTreeWinSeparator            = hl(c_dark.bg3, nil),
    NvimTreeRootFolder              = hl(c_dark.red, nil, {bold=true}),
    NvimTreeFolderIcon              = hl(c_dark.red, nil),
    NvimTreeFolderName              = hl(c_dark.fg,  nil),
    NvimTreeOpenedFolderName        = hl(c_dark.fg,  nil, {bold=true}),
    NvimTreeFileName                = hl(c_dark.fg,  nil),
    NvimTreeOpenedFile              = hl(c_dark.red, nil),
    NvimTreeGitNew                  = hl(c_dark.green,  nil),
    NvimTreeGitDirty                = hl(c_dark.yellow, nil),
    NvimTreeGitDeleted              = hl(c_dark.red,    nil),
    NvimTreeGitStaged               = hl(c_dark.green,  nil),
    NvimTreeIndentMarker            = hl(c_dark.bg3, nil),

    -- ── render-markdown ──────────────────────────────────────────────────────
    RenderMarkdownH1Bg              = hl(c_dark.red,    "#2a1a1a", {bold=true}),
    RenderMarkdownH2Bg              = hl(c_dark.red,    "#2a1a1a", {bold=true}),
    RenderMarkdownH3Bg              = hl(c_dark.orange, "#2a2222", {bold=true}),
    RenderMarkdownH4Bg              = hl(c_dark.orange, "#2a2222"),
    RenderMarkdownH5Bg              = hl(c_dark.fg2,    c_dark.bg1),
    RenderMarkdownH6Bg              = hl(c_dark.fg3,    c_dark.bg1),
    RenderMarkdownH1                = hl(c_dark.red,    nil, {bold=true}),
    RenderMarkdownH2                = hl(c_dark.red,    nil, {bold=true}),
    RenderMarkdownH3                = hl(c_dark.orange, nil, {bold=true}),
    RenderMarkdownCode              = hl(nil,           c_dark.bg1),
    RenderMarkdownCodeBorder        = hl(c_dark.bg3,    nil),
    RenderMarkdownCodeInline        = hl(c_dark.fg2,    c_dark.bg1),
    RenderMarkdownMath              = hl(c_dark.teal,   nil),
    RenderMarkdownBullet            = hl(c_dark.red,    nil),
    RenderMarkdownDash              = hl(c_dark.bg3,    nil),
    RenderMarkdownLink              = hl(c_dark.blue,   nil, {underline=true}),
    RenderMarkdownChecked           = hl(c_dark.green,  nil),
    RenderMarkdownUnchecked         = hl(c_dark.fg3,    nil),
    RenderMarkdownQuote             = hl(c_dark.fg2,    nil, {italic=true}),
    RenderMarkdownTableHead         = hl(c_dark.teal,   nil, {bold=true}),
    RenderMarkdownTableRow          = hl(c_dark.fg,     nil),
    RenderMarkdownTableFill         = hl(c_dark.bg3,    nil),
    RenderMarkdownDef               = hl(c_dark.red,    nil),
    RenderMarkdownThm               = hl(c_dark.blue,   nil),
    RenderMarkdownLem               = hl(c_dark.teal,   nil),
    RenderMarkdownProp              = hl(c_dark.green,  nil),
    RenderMarkdownCol               = hl(c_dark.purple, nil),
    RenderMarkdownPf                = hl(c_dark.fg3,    nil),

    -- ── base46 statusline: grayscale and red mode accents ────────────────────
    -- base46 convention: Mode={fg=black,bg=col,bold}, ModeSep={fg=col,bg=grey}
    ST_EmptySpace            = hl("#414141", "#303030"),
    St_NormalMode            = hl("#1e1e1e", "#ffffff", {bold=true}),
    St_NormalModeSep         = hl("#ffffff", "#414141"),
    St_InsertMode            = hl("#1e1e1e", "#ff5c5c", {bold=true}),
    St_InsertModeSep         = hl("#ff5c5c", "#414141"),
    St_VisualMode            = hl("#1e1e1e", "#b0b0b0", {bold=true}),
    St_VisualModeSep         = hl("#b0b0b0", "#414141"),
    St_ReplaceMode           = hl("#f5f5f5", "#a52f2f", {bold=true}),
    St_ReplaceModeSep        = hl("#a52f2f", "#414141"),
    St_SelectMode            = hl("#1e1e1e", "#eeeeee", {bold=true}),
    St_SelectModeSep         = hl("#eeeeee", "#414141"),
    St_TerminalMode          = hl("#1e1e1e", "#8f8f8f", {bold=true}),
    St_TerminalModeSep       = hl("#8f8f8f", "#414141"),
    St_NTerminalMode         = hl("#1e1e1e", "#d76a6a", {bold=true}),
    St_NTerminalModeSep      = hl("#d76a6a", "#414141"),
    St_CommandMode           = hl("#1e1e1e", "#ff4444", {bold=true}),
    St_CommandModeSep        = hl("#ff4444", "#414141"),
    St_ConfirmMode           = hl("#f5f5f5", "#8f3030", {bold=true}),
    St_ConfirmModeSep        = hl("#8f3030", "#414141"),
    St_EmptySpace            = hl("#414141", "#303030"),
    St_file                  = hl("#d3d3d3", "#303030"),
    St_file_sep              = hl("#303030", nil),
    St_cwd_text              = hl("#d3d3d3", "#303030"),
    St_gitIcons              = hl("#ffffff", nil),
    St_Lsp                   = hl("#ffffff", nil),
    St_LspMsg                = hl("#c9c9c9", nil),
    St_LspInfo               = hl("#eeeeee", nil),
    St_lspError              = hl("#ff6464", nil),
    St_lspWarning            = hl("#d76a6a", nil),
    St_LspHints              = hl("#555555", nil),
    St_pos_sep               = hl("#ff4444", "#303030"),
    St_pos_icon              = hl("#1e1e1e", "#ff4444"),
    St_pos_text              = hl("#ff4444", "#303030"),

    -- ── devicon overrides ─────────────────────────────────────────────────────
    DevIconCpp               = hl("#d0d0d0", nil),
    DevIconCppm              = hl("#b0b0b0", nil),
    DevIconts                = hl("#ff4d4d", nil),
}

M.dark_highlights = dark

-- Reload render-markdown's cached combined highlight groups and re-render all
-- open markdown buffers. Must be called after highlight groups are updated.
local function refresh_render_markdown()
    local ok_colors, rm_colors = pcall(require, 'render-markdown.core.colors')
    if ok_colors then rm_colors.reload() end

    local ok_api, rm_api = pcall(require, 'render-markdown')
    if not ok_api then return end
    for _, buf in ipairs(vim.api.nvim_list_bufs()) do
        if vim.api.nvim_buf_is_loaded(buf)
            and vim.bo[buf].filetype == 'markdown'
        then
            pcall(rm_api.render, { buf = buf, event = 'ThemeToggle' })
        end
    end
end

-- Apply the single dark theme at startup and after base46 reloads.
function M.init()
    for group, opts in pairs(dark) do
        vim.api.nvim_set_hl(0, group, opts)
    end
    vim.schedule(refresh_render_markdown)
end

return M
